services:
  - type: web
    name: holship-rms
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    # Auto-run pending Prisma migrations before starting the app
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
      # Legg til disse i Render dashboardet med riktige verdier:
      # - DATABASE_URL
      # - JWT_SECRET
      # - O365_USER
      # - O365_PASS
      # - O365_HOST (smtp.office365.com)
      # - O365_PORT (587)
      # - O365_SECURE (false)
      # - MAIL_FROM
      # - MAIL_BCC (valgfri)
      # Valgfrie stylingvariabler for e-postmal:
      # - MAIL_TEMPLATE_WIDTH (standard 420)
      # - MAIL_LOGO_MAX_HEIGHT (standard 20)
      # - MAIL_FROM_NAME (f.eks. "HOLSHIP RMS")
